name: 心灵纽带NeuraLink CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 Node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 安装前端依赖
      run: |
        cd frontend
        npm install
        
    - name: 构建前端
      run: |
        cd frontend
        npm run build
        
    - name: 安装后端依赖
      run: |
        cd backend
        npm install
        
    - name: 构建后端
      run: |
        cd backend
        npm run build
        
    - name: 运行测试
      run: |
        cd backend
        npm test
        
    - name: 构建 Docker 镜像
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: neuralink:latest
        
    - name: 登录到 Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: 推送 Docker 镜像
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/neuralink:latest
        
    - name: 部署到 Vercel
      if: github.event_name != 'pull_request'
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./